<!-- ****** Infinite Menus Structure & Links ***** -->
<div style="width:700px;"><div class="imcm imde" id="imouter0"><ul id="imenus0">

<li  style="width:60px;" title="Home"><a href="/">HOME</a></li>
<li  style="width:85px;" title="About Us"><a href="about_us.php">ABOUT US</a></li>
<li  style="width:85px;" title="Forgings"><a href="closed_die_forging.php"><div class="imea imeam"><div></div></div>FORGINGS</a>
						<div class="imsc"> 
                        <div class="imsubc" style="width:102px;top:-1px;left:0px;"> 
                          <ul style="">
                            <li title="Valve Stems"><a href="valve_stem.php">Valve Stems</a></li></ul></div></div></li>
<li  style="width:155px;" title="Product Categories"><a><div class="imea imeam"><div></div></div>PRODUCT PORTFOLIO</a>
	                  <div class="imsc"> 
                        <div class="imsubc" style="width:159px;top:-1px;left:0px;"> 
                          <ul style="">
                            <li title="Fasteners"> <a href="fasteners.php"> 
                              <div class="imea imeas"> 
                                <div></div>
                              </div>
                              Fasteners</a> 
                              <div class="imsc"> 
                                <div class="imsubc" style="width:171px;top:-27px;left:153px;"> 
                                  <ul style="">
                                    <li title="Eye Bolts"><a href="eyebolts.php">Eye Bolts</a></li>
                                    <li title="Bolts"><a href="bolts.php">Bolts</a></li>
                                    <li title="Pins"><a href="pins.php">Pins</a></li>
                                  </ul>
                                </div>
                              </div>
                            </li>
                            <li title="Gear Blank"><a href="gear_blank.php"> 
                              <div class="imea imeas"> 
                                <div></div>
                              </div>
                              Gear Blank</a> 
                              <div class="imsc"> 
                                <div class="imsubc" style="width:150px;top:-27px;left:153px;"> 
                                  <ul style="">
                                    <li title="Gear Shaft"><a href="gear_shaft.php">Gear 
                                      Shaft</a></li>
                                    <li title="Crab Bolts"><a href="crab_bolt.php">Crab 
                                      Bolts</a></li>
                                  </ul>
                                </div>
                              </div>
                            </li>
                            <li title="Railroad Components"><a href="railroad_components.php"> 
                              <div class="imea imeas"> 
                                <div></div>
                              </div>
                              Railroad Components</a> 
                              <div class="imsc"> 
                                <div class="imsubc" style="width:150px;top:-27px;left:153px;"> 
                                  <ul style="">
                                    <li title="Machined Socket"><a href="machined_socket.php">Machined 
                                      Socket</a></li>
                                    <li title="Hand Holds"><a href="hand_holds.php">Hand 
                                      Holds</a></li>
                                    <li title="Sill Step"><a href="sill_step.php">Sill 
                                      Step</a></li>
                                  </ul>
                                </div>
                              </div>
                            </li>
                            <li title="Construction Components"><a href="construction_component.php">
                              <div class="imea imeas"> 
                                <div></div>
                              </div>
                              Construction Component</a> 
                              <div class="imsc"> 
                                <div class="imsubc" style="width:150px;top:-27px;left:153px;"> 
                                  <ul style="">
                                    <li title="Torque Anchor Forging"><a href="torque_anchor_forging.php">Torque 
                                      Anchor Forging</a></li>
                                    <li title="Auger Tuber Forging"><a href="auger_tuber_forging.php">Auger 
                                      Tuber Forging</a></li>
                                  </ul>
                                </div>
                              </div>
                            </li>
                            <li title="Ride Control"><a href="ride_control.php"> 
                              <div class="imea imeas"> 
                                <div></div>
                              </div>
                              Ride Control</a> 
                              <div class="imsc"> 
                                <div class="imsubc" style="width:150px;top:-27px;left:153px;"> 
                                  <ul style="">
                                    <li title="Strut "><a href="strut.php">Strut</a></li>
                                    <li title="Torsion Bars"><a href="torsion_bars.php">Torsion 
                                      Bars</a></li>
                                    <li title="Drag Link Forging"><a href="drag_link_forging.php">Drag 
                                      Link Forging</a></li>
                                    <li title="Tie Rod Forging"><a href="tie_rod_forging.php">Tie 
                                      Rod Forging</a></li>
                                    <li title="Stabilizer Bars"><a href="stabilizer_bars.php">Stabilizer 
                                      Bars</a></li>
                                  </ul>
                                </div>
                              </div>
                            </li>
                          </ul>
                        </div>
                      </div>
      </li>

	
<li  style="width:155px;" title="Mission Statement"><a href="vision_mission.php"><div class="imea imeam"><div></div></div>MISSION STATEMENT</a></li>

<li  style="width:135px;" title="Contact Us"><a href="contact_us.php"><div class="imea imeam"><div></div></div>CONTACT US</a></li>

</ul></div></div>

<script language="JavaScript" src="kdkjs-2.js" type="text/javascript"></script>             